<a href="https://colab.research.google.com/github/18252054-sketch/eda_projeto_ia/blob/main/Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1ª Etapa do Projeto - Análise Exploratória de Dados (EDA)

### 1) **(5%)** Qual a base escolhida e qual seu interesse nela?

# https://www.kaggle.com/datasets/adaoduque/campeonato-brasileiro-de-futebol

### 2) **(5%)** Descrição básica do conjunto de dados escolhido pelo aluno (1 parágrafo).
- Identificação da variável a serem trabalhadas
- Classificação das variáveis como: contínua ou discreta.

### 3) **(15%)** Faça uma avaliação descritiva da sua base. Quantas linhas ela possui? Quais os tipos de dados? Quantas e quais features possuem?

Cada variável escolhida pelo aluno precisa passar por ao menos 1 pré-processamento. O pré-processamento pode ser (mas não está limitado a):
- Checagem se os valores estão dentro de um limite permitido ou razoável.
- Tratamento de valores ausentes por eliminação ou substituição.
- Conversão do tipo de dados.

### 4) **(60%)** Nos blocos seguintes construa análises que vão justificar suas conclusões.

#### 4.1) **(20%)** Análise 1 -  Distribuição dos valores para cada uma das variáveis
- Exemplo para variável contínua: se o conjunto de dados possui a variável "idade". Quantos % possui a idade entre 0 e 30 anos? 31 a 59? 60+?

- Exemplo para variável discreta: se o conjunto de dados possui a variável "gênero", quantos % do conjunto de dados é do sexo feminino, quantos % é masculino? Inclua outros gêneros se houver.

#### 4.2) **(20%)** Análise 2 - Dependência entre variáveis
O aluno deve apresentar as mesmas distribuições para cada valor da variável dependente. Exemplo: Em um conjunto de dados em que as variáveis independentes são idade e sexo, e a variável dependente é renda. O aluno pode dividir a renda em 3 "grupos", <1000 reais, entre 1000 e 10000 reais e >1000 reais. Para cada um desses grupos, é necessário apresentar a distribuição das variáveis "idade" e "sexo".

#### 4.3) **(20%)** Análise 3 - Correlação entre variáveis

O aluno deve apresentar 3 análises de correlação entre variáveis do conjunto de dados trabalhado. Exemplo: Em um conjunto de dados com as informações de temperatura e ocorrência de incêndios, eu gostaria de saber a incidência de correlação entre as duas variáveis.

### 5) Conclusões **15%**

*O que é possível concluir com os dados que você analisou? Se fosse fazer uma apresentação, o que levaria como os maiores destaques e por que?*

In [3]:
import pandas as pd
import numpy as np

In [13]:
import os
import kagglehub
import pandas as pd

# 1. Download do dataset do Kaggle
path = kagglehub.dataset_download("felipesembay/sofascore-and-transfermarkt-football-data")
print("Caminho dos ficheiros:", path)

# 2. Listar todos os ficheiros CSV disponíveis na base
ficheiros = os.listdir(path)
print("\nFicheiros CSV encontrados na base:")
for f in ficheiros:
    print(f"- {f}")

# 3. Exemplo: Carregar a tabela de estatísticas de jogadores (statistics_player.csv)
csv_player_stats = os.path.join(path, "statistics_player.csv")

if os.path.exists(csv_player_stats):
    df_players = pd.read_csv(csv_player_stats)

    print("\n=== VALIDAÇÃO DA TABELA STATISTICS_PLAYER ===")
    print(f"Total de Linhas: {df_players.shape[0]}")
    print(f"Total de Colunas: {df_players.shape[1]}")

    # Exibir as 5 primeiras linhas
    display(df_players.head())

Downloading to /root/.cache/kagglehub/datasets/felipesembay/sofascore-and-transfermarkt-football-data/1.archive...

100%|██████████| 3.34M/3.34M [00:00<00:00, 85.8MB/s]

Extracting files...
Caminho dos ficheiros: /root/.cache/kagglehub/datasets/felipesembay/sofascore-and-transfermarkt-football-data/versions/1

Ficheiros CSV encontrados na base:
- players_tm.csv
- market_value.csv
- statistics_player.csv
- partidas_sofascore.csv
- statistics_game.csv
- performance_tm.csv

=== VALIDAÇÃO DA TABELA STATISTICS_PLAYER ===
Total de Linhas: 39861
Total de Colunas: 53

,id_partida,data_jogo,campeonato,team,team_name,name,position,jerseyNumber,height,country,...,shotOffTarget,interceptionWon,keyPass,dispossessed,blockedScoringAttempt,bigChanceCreated,penaltyWon,totalOffside,goalsPrevented,penaltyConceded
0,12117250,2024-09-29,Brasileirão Série A,home,São Paulo,Rafael,G,23.0,192.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1379,NaN
1,12117250,2024-09-29,Brasileirão Série A,home,São Paulo,Rafinha,D,13.0,172.0,Brazil,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12117250,2024-09-29,Brasileirão Série A,home,São Paulo,Robert Arboleda,D,5.0,187.0,Ecuador,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12117250,2024-09-29,Brasileirão Série A,home,São Paulo,Alan Franco,D,28.0,183.0,Argentina,...,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12117250,2024-09-29,Brasileirão Série A,home,São Paulo,Welington,D,6.0,170.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# 1. Informações de tipos e memória
print("=== INFORMAÇÕES DA BASE DE DADOS ===")
print(f"Linhas: {df_players.shape[0]} | Colunas: {df_players.shape[1]}")
print("\n--- Tipos de Dados e Nulos por Coluna ---")
print(df_players.info())

# 2. Contagem detalhada de valores ausentes (Nulos)
print("\n--- Contagem de Valores Nulos ---")
nulos = df_players.isnull().sum()
print(nulos[nulos > 0]) # Exibe apenas colunas que possuem nulos

# 3. Verificação de registros duplicados
print(f"\nLinhas duplicadas encontradas: {df_players.duplicated().sum()}")

=== INFORMAÇÕES DA BASE DE DADOS ===
Linhas: 39861 | Colunas: 53

--- Tipos de Dados e Nulos por Coluna ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39861 entries, 0 to 39860
Data columns (total 53 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_partida                  39861 non-null  int64
 1   data_jogo                   39861 non-null  object
 2   campeonato                  39861 non-null  object
 3   team                        39861 non-null  object
 4   team_name                   39861 non-null  object
 5   name                        39861 non-null  object
 6   position                    39779 non-null  object
 7   jerseyNumber                39499 non-null  float64
 8   height                      38697 non-null  float64
 9   country                     39688 non-null  object
 10  dateOfBirth                 39731 non-null  object
 11  age                         39731 non-null  float64
 12  totalPass                   27383 non-null  float64
 13  accuratePass                27102 non-null  float64
 14  totalLongBalls              20500 non-null  float64
 15  accurateLongBalls           16635 non-null  float64
 16  goalAssist                  21054 non-null  float64
 17  goals                       1879 non-null   float64
 18  minutesPlayed               27765 non-null  float64
 19  rating                      27377 non-null  float64
 20  touches                     27637 non-null  float64
 21  possessionLostCtrl          26758 non-null  float64
 22  expectedGoals               6001 non-null   float64
 23  expectedAssists             8447 non-null   float64
 24  aerialLost                  13897 non-null  float64
 25  aerialWon                   13209 non-null  float64
 26  duelLost                    23123 non-null  float64
 27  duelWon                     23253 non-null  float64
 28  onTargetScoringAttempt      5932 non-null   float64
 29  totalClearance              13763 non-null  float64
 30  totalTackle                 14469 non-null  float64
 31  wasFouled                   12934 non-null  float64
 32  fouls                       13966 non-null  float64
 33  totalCross                  12028 non-null  float64
 34  accurateCross               5335 non-null   float64
 35  outfielderBlock             4327 non-null   float64
 36  goodHighClaim               807 non-null    float64
 37  savedShotsFromInsideTheBox  1423 non-null   float64
 38  saves                       1666 non-null   float64
 39  challengeLost               9011 non-null   float64
 40  totalContest                12757 non-null  float64
 41  wonContest                  8288 non-null   float64
 42  bigChanceMissed             1531 non-null   float64
 43  shotOffTarget               7505 non-null   float64
 44  interceptionWon             9486 non-null   float64
 45  keyPass                     10650 non-null  float64
 46  dispossessed                9455 non-null   float64
 47  blockedScoringAttempt       4815 non-null   float64
 48  bigChanceCreated            1907 non-null   float64
 49  penaltyWon                  145 non-null    float64
 50  totalOffside                2345 non-null   float64
 51  goalsPrevented              793 non-null    float64
 52  penaltyConceded             216 non-null    float64
dtypes: float64(44), int64(1), object(8)
memory usage: 16.1+ MB
None

--- Contagem de Valores Nulos ---
position                         82
jerseyNumber                    362
height                         1164
country                         173
dateOfBirth                     130
age                             130
totalPass                     12478
accuratePass                  12759
totalLongBalls                19361
accurateLongBalls             23226
goalAssist                    18807
goals                         37982
minutesPlayed                 12096
rating                        12484
touches                       12224
possessionLostCtrl            13103
expectedGoals                 33860
expectedAssists               31414
aerialLost                    25964
aerialWon                     26652
duelLost                      16738
duelWon                       16608
onTargetScoringAttempt        33929
totalClearance                26098
totalTackle                   25392
wasFouled                     26927
fouls                         25895
totalCross                    27833
accurateCross                 34526
outfielderBlock               35534
goodHighClaim                 39054
savedShotsFromInsideTheBox    38438
saves                         38195
challengeLost                 30850
totalContest                  27104
wonContest                    31573
bigChanceMissed               38330
shotOffTarget                 32356
interceptionWon               30375
keyPass                       29211
dispossessed                  30406
blockedScoringAttempt         35046
bigChanceCreated              37954
penaltyWon                    39716
totalOffside                  37516
goalsPrevented                39068
penaltyConceded               39645
dtype: int64

Linhas duplicadas encontradas: 138

In [15]:
# Resumo estatístico das variáveis numéricas (notas, gols, passes, etc.)
print("=== RESUMO ESTATÍSTICO NUMÉRICO ===")
df_players.describe().T

=== RESUMO ESTATÍSTICO NUMÉRICO ===

,count,mean,std,min,25%,50%,75%,max
id_partida,39861.0,1.219811e+07,131559.762758,1.211697e+07,1.211723e+07,1.214642e+07,1.217249e+07,1.294381e+07
jerseyNumber,39499.0,2.408347e+01,22.722222,1.000000e+00,8.000000e+00,1.800000e+01,3.000000e+01,1.000000e+02
height,38697.0,1.801876e+02,7.056976,1.560000e+02,1.750000e+02,1.800000e+02,1.850000e+02,2.040000e+02
age,39731.0,2.723090e+01,5.023548,1.600000e+01,2.300000e+01,2.700000e+01,3.100000e+01,4.400000e+01
totalPass,27383.0,2.597637e+01,18.922088,1.000000e+00,1.100000e+01,2.200000e+01,3.600000e+01,1.360000e+02
accuratePass,27102.0,2.114792e+01,16.853232,1.000000e+00,8.000000e+00,1.700000e+01,3.000000e+01,1.250000e+02
totalLongBalls,20500.0,4.789756e+00,4.490836,1.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00,3.800000e+01
accurateLongBalls,16635.0,2.785993e+00,2.192823,1.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,1.900000e+01
goalAssist,21054.0,6.549824e-02,0.257383,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
goals,1879.0,1.063864e+00,0.253134,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00
minutesPlayed,27765.0,6.310149e+01,30.369680,1.000000e+00,3.200000e+01,7.700000e+01,9.000000e+01,9.000000e+01
rating,27377.0,6.881806e+00,0.493158,3.000000e+00,6.600000e+00,6.800000e+00,7.100000e+00,1.000000e+01
touches,27637.0,3.735536e+01,23.196124,1.000000e+00,1.900000e+01,3.500000e+01,5.300000e+01,1.490000e+02
possessionLostCtrl,26758.0,8.538269e+00,5.346059,1.000000e+00,4.000000e+00,8.000000e+00,1.200000e+01,3.900000e+01
expectedGoals,6001.0,1.612968e-01,0.233913,3.000000e-03,3.050000e-02,7.120000e-02,1.772000e-01,2.019400e+00
expectedAssists,8447.0,7.727456e-02,0.118032,5.001840e-03,1.205650e-02,2.880490e-02,8.615800e-02,1.284370e+00
aerialLost,13897.0,1.836511e+00,1.266644,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.500000e+01
aerialWon,13209.0,1.932319e+00,1.364779,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.500000e+01
duelLost,23123.0,3.747957e+00,2.483394,1.000000e+00,2.000000e+00,3.000000e+00,5.000000e+00,2.000000e+01
duelWon,23253.0,3.727175e+00,2.465478,1.000000e+00,2.000000e+00,3.000000e+00,5.000000e+00,2.500000e+01
onTargetScoringAttempt,5932.0,1.261463e+00,0.565320,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,6.000000e+00
totalClearance,13763.0,2.480201e+00,2.037994,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,2.400000e+01
totalTackle,14469.0,1.885963e+00,1.198557,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.200000e+01
wasFouled,12934.0,1.657724e+00,1.005888,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+01
fouls,13966.0,1.613776e+00,0.895816,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,8.000000e+00
totalCross,12028.0,2.718823e+00,2.274083,1.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,2.100000e+01
accurateCross,5335.0,1.484536e+00,0.849190,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,8.000000e+00
outfielderBlock,4327.0,1.295355e+00,0.625128,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,6.000000e+00
goodHighClaim,807.0,1.478315e+00,0.759857,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,6.000000e+00
savedShotsFromInsideTheBox,1423.0,2.130710e+00,1.209924,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,8.000000e+00
saves,1666.0,3.248499e+00,1.869483,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,1.200000e+01
challengeLost,9011.0,1.420153e+00,0.743548,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,7.000000e+00
totalContest,12757.0,2.017089e+00,1.490176,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,2.000000e+01
wonContest,8288.0,1.544160e+00,0.952209,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.100000e+01
bigChanceMissed,1531.0,1.124755e+00,0.367976,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.000000e+00
shotOffTarget,7505.0,1.294337e+00,0.605458,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.000000e+00
interceptionWon,9486.0,1.516340e+00,0.847519,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,8.000000e+00
keyPass,10650.0,1.583568e+00,0.949773,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+01
dispossessed,9455.0,1.518773e+00,0.865287,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.000000e+00
blockedScoringAttempt,4815.0,1.192939e+00,0.480997,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.000000e+00
bigChanceCreated,1907.0,1.088096e+00,0.310028,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.000000e+00
penaltyWon,145.0,1.020690e+00,0.142837,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00
totalOffside,2345.0,1.191045e+00,0.496752,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.000000e+00
goalsPrevented,793.0,1.116166e-01,0.705579,-2.869300e+00,-3.112000e-01,1.377000e-01,5.217000e-01,2.941700e+00
penaltyConceded,216.0,1.009259e+00,0.096001,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00